export const SET_REMAINING_MONEY = 'SET_REMAINING_MONEY';
export const SHOW_FAMILY_FORM = 'SHOW_FAMILY_FORM';
export const SUBMIT_FAMILY_FORM = 'SUBMIT_FAMILY_FORM';
export const LIST_FAMILIES = 'LIST_FAMILIES';
export const SHOW_RESOLVE_BUTTON = 'SHOW_RESOLVE_BUTTON';
export const RESOLVE_ACTION = 'RESOLVE_ACTION';
